sources:
  # - name: ethereum-exchange
  #   handler:
  #     graphql:
  #       endpoint: https://api.thegraph.com/subgraphs/name/sushiswap/exchange
  #   transforms:
  #     - prefix:
  #         value: ETHEREUM_
  #         includeRootOperations: true
  #         ignore:
  #           - _SubgraphErrorPolicy_
  #     - typeMerging:
  #         queryFields:
  #           - queryFieldName: ETHEREUM_factory
  #             keyField: id
  #             keyArg: id
  - name: bentobox
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/matthewlilley/bentobox-ethereum
    # transforms:
    #   - prefix:
    #       value: ETHEREUM_
    #       includeRootOperations: true
    #       ignore:
    #         - _SubgraphErrorPolicy_
      # - typeMerging:
      #     queryFields:
      #       - queryFieldName: ETHEREUM_bentoBox
      #         keyField: id
      #         keyArg: id
documents:
  - ./query.graphql