sources:
  - name: bentobox
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/matthewlilley/bentobox-polygon
      transforms:
      - typeMerging:
          queryFields:
            - queryFieldName: tokens
              keyField: id
              keyArg: ids
  - name: exchange
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/sushiswap/legacy-exchange-polygon
    transforms:
      - typeMerging:
          queryFields:
            - queryFieldName: tokens
              keyField: id
              keyArg: ids
  - name: trident
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/matthewlilley/trident
    transforms:
      - filterSchema:
        mode: wrap
        filters:
          - Type.!{BentoBox, Strategy, StrategyHarvest, Rebase, FlashLoan, Clone, MasterContractApproval, Protocol, User, UserToken, Transaction}
      - typeMerging:
          queryFields:
            - queryFieldName: tokens
              keyField: id
              keyArg: ids
documents:
  - ./query.graphql